"""create node positions table

Revision ID: fe32e6c02885
Revises: 4b2c6b10128
Create Date: 2025-06-15 17:33:04.681976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe32e6c02885'
down_revision = '4b2c6b10128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_positions_id'), 'node_positions', ['id'], unique=False)
    op.create_index(op.f('ix_node_positions_node_id'), 'node_positions', ['node_id'], unique=False)
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_constraint(op.f('fk_feature_parent'), 'features', type_='foreignkey')
    op.create_foreign_key(None, 'features', 'features', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.create_foreign_key(op.f('fk_feature_parent'), 'features', 'features', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tested', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('high', 'normal', 'low', name='priorityenum'), server_default=sa.text("'normal'::priorityenum"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('tests_feature_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tests_pkey'))
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.drop_index(op.f('ix_node_positions_node_id'), table_name='node_positions')
    op.drop_index(op.f('ix_node_positions_id'), table_name='node_positions')
    op.drop_table('node_positions')
    # ### end Alembic commands ### 